server:
  port: 8080
spring:
  application:
    name: ShopApp-BE
  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username: root
    password: 123456789a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
        client:
          registration:
            google:
              client-id: 567381700445-7gr2kvq4posh4f1fhca0fu3pv5qsvdmn.apps.googleusercontent.com
              client-secret: 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
              redirect-uri: http://localhost:3000/authenticate
              user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
              token-uri: https://oauth2.googleapis.com/token
              scope: profile, email, https://www.googleapis.com/auth/user.phonenumbers.read

            facebook:
              client-id: 639375768955190
              client-secret: 1e366421bb07788e6dbc01a83b0bb4bf
              redirect-uri: http://localhost:3000/authenticate
              user-info-uri: https://graph.facebook.com/me?fields=id,name,email,picture.type(large),birthday
              token-uri: https://graph.facebook.com/v3.0/oauth/access_token

  mail:
    host: smtp.gmail.com
    port: 587
    username: daongocson12022004@gmail.com
    password: azbl ywtt lvsc ahpj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable : true
            required: true


api:
  prefix: /api/v1
file:
  url: http://localhost:8080/uploads/
  dir: D:/uploads/ShopApp-BE/

jwt:
  expiration: 1800
  expiration-refresh-token: 86400
  expiration-reset-token: 300
  secret-key: "RIw1DJ/txeArNX2Nf6CmAbxobAI5LH9Qc1HJagsurGPiZROq91Ywe+2zKJ1fn1Ta"
  refresh-key: "/LUlafmFDnG8hvW2ffNwk6zzzoJ+m3KLn3LVKoVzuWJVxHW2HqM74mGl9RsFKgCG"
  reset-key : "oObnn/FToWBrFtOMaflVzzAnb4nJpu91Lp8CtDw6z35U5sJHaRqwaZIAGWRp+GP6"


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.oauth2: DEBUG
    org.hibernate: ERROR



