server:
  port: 8080
spring:
  application:
    name: ShopApp-BE
  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username: root
    password: 123456789a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true


api:
  prefix: /api/v1
file:
  url: http://localhost:8080/uploads/
  dir: D:/uploads/ShopApp-BE/

jwt:
  expiration: 30
  expiration-refresh-token: 86400
  secret-key: "RIw1DJ/txeArNX2Nf6CmAbxobAI5LH9Qc1HJagsurGPiZROq91Ywe+2zKJ1fn1Ta"
  refresh-key: "/LUlafmFDnG8hvW2ffNwk6zzzoJ+m3KLn3LVKoVzuWJVxHW2HqM74mGl9RsFKgCG"

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR



