server:
  port: 8080
spring:
  application:
    name: ShopApp-BE
  datasource:
    url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
    username: root
    password: 123456789a
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: daongocson12022004@gmail.com
    password: azbl ywtt lvsc ahpj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable : true
            required: true


api:
  prefix: /api/v1
file:
  url: http://localhost:8080/uploads/
  dir: D:/uploads/ShopApp-BE/

jwt:
  expiration: 1800
  expiration-refresh-token: 86400
  expiration-reset-token: 300
  secret-key: "RIw1DJ/txeArNX2Nf6CmAbxobAI5LH9Qc1HJagsurGPiZROq91Ywe+2zKJ1fn1Ta"
  refresh-key: "/LUlafmFDnG8hvW2ffNwk6zzzoJ+m3KLn3LVKoVzuWJVxHW2HqM74mGl9RsFKgCG"
  reset-key : "oObnn/FToWBrFtOMaflVzzAnb4nJpu91Lp8CtDw6z35U5sJHaRqwaZIAGWRp+GP6"


logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.hibernate: ERROR



